apiVersion: v1
kind: Pod
metadata:
  name: health-probe-app
  labels:
    app: health-probe-app
spec:
  containers:
  - name: health-probe-container
    image: nginxdemos/hello
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5