apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-autoscale
  template:
    metadata:
      labels:
        app: nginx-autoscale
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"