apiVersion: v1
kind: Pod
metadata:
  name: taint-demo-pod
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "team"
    operator: "Equal"
    value: "dev"
    effect: "NoSchedule"
